import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
export { THREE };
export const $=s=>document.querySelector(s);
export const ui={status:$("#status"),room:$("#room"),venue:$("#venue"),venueMeta:$("#venue-meta"),viewpoints:$("#viewpoints"),venueTools:$("#venue-tools"),recentDevices:$("#recent-devices"),recentDevicesWrap:$("#recent-devices-wrap"),recentRooms:$("#recent-rooms"),recentRoomsWrap:$("#recent-rooms-wrap"),deviceName:$("#device-name"),deviceId:$("#device-id"),receiverState:$("#receiver-state"),shareState:$("#share-state"),hudVenue:$("#hud-venue"),hudView:$("#hud-view"),hudScreen:$("#hud-screen"),hudStream:$("#hud-stream"),hudPeer:$("#hud-peer")};
export const status=(m,l="info")=>{ui.status.textContent=m;ui.status.dataset.level=l};
export const renderer=new THREE.WebGLRenderer({canvas:$("#stage"),antialias:true,powerPreference:"high-performance"});
renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.75));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.xr.enabled=true;renderer.xr.setReferenceSpaceType("local-floor");
export const scene=new THREE.Scene();scene.background=new THREE.Color(0x050608);scene.fog=new THREE.Fog(0x050608,11,38);
export const rig=new THREE.Group();scene.add(rig);export const camera=new THREE.PerspectiveCamera(54,innerWidth/innerHeight,.05,100);rig.add(camera);
export const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=1.1;controls.maxDistance=30;
scene.add(new THREE.HemisphereLight(0xcbdcff,0x10131a,1.7));const key=new THREE.DirectionalLight(0xffffff,2.4);key.position.set(4,8,5);scene.add(key);
export const floor=new THREE.Mesh(new THREE.PlaneGeometry(40,40),new THREE.MeshStandardMaterial({color:0x0d1015,roughness:.94}));floor.rotation.x=-Math.PI/2;scene.add(floor);const grid=new THREE.GridHelper(40,80,0x34404d,0x171d25);grid.position.y=.003;scene.add(grid);
const venueGroup=new THREE.Group(),screenGroup=new THREE.Group();scene.add(venueGroup,screenGroup);
export const video=document.createElement("video");Object.assign(video,{playsInline:true,autoplay:true,muted:true,preload:"auto"});video.setAttribute("playsinline","");video.setAttribute("webkit-playsinline","");
const standby=new THREE.MeshBasicMaterial({color:0x111820,toneMapped:false,side:THREE.DoubleSide});let videoTexture=null,activeSource="none";
const videoPlane=new THREE.Mesh(new THREE.PlaneGeometry(3.2,1.8),standby),frame=new THREE.Mesh(new THREE.BoxGeometry(3.38,1.98,.1),new THREE.MeshStandardMaterial({color:0x11161d,roughness:.5,metalness:.35}));videoPlane.position.z=.056;screenGroup.add(frame,videoPlane);
const fallback=[{id:"quick-16x9",name:"快速测试 · 16:9",modelUrl:null,screen:{widthM:3.2,heightM:1.8,resolution:[1920,1080],position:[0,1.75,.05]},stage:{widthM:5.4,depthM:2.4,type:"blackbox"},viewpoints:[{id:"audience",label:"观众位",position:[0,1.65,5.8],target:[0,1.65,.05]},{id:"foh",label:"控台位",position:[0,1.65,8.2],target:[0,1.65,.05]},{id:"stage-left",label:"舞台左",position:[-3.7,1.65,1.8],target:[0,1.65,.05]},{id:"stage-right",label:"舞台右",position:[3.7,1.65,1.8],target:[0,1.65,.05]},{id:"screen-front",label:"屏前",position:[0,1.65,2.4],target:[0,1.65,.05]}]}];
export let venues=fallback,currentVenue=fallback[0],currentView="audience",mode="quick";const loader=new GLTFLoader();
function box(p,x,y,z,sx,sy,sz,color=0x141922){const m=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),new THREE.MeshStandardMaterial({color,roughness:.8,metalness:.18}));m.position.set(x,y,z);p.add(m);return m}
function clearVenue(){while(venueGroup.children.length){const o=venueGroup.children.pop();o.traverse?.(n=>{n.geometry?.dispose?.();Array.isArray(n.material)?n.material.forEach(m=>m.dispose?.()):n.material?.dispose?.()})}}
function procedural(v){clearVenue();const w=v.stage?.widthM||v.screen.widthM+2.2,d=v.stage?.depthM||2.8,t=v.stage?.type||"blackbox";box(venueGroup,0,.18,.2,w,.36,d,0x0a0d12);if(t==="gallery"){box(venueGroup,0,2.2,-.32,w+1.2,4.4,.18,0x1c2027);box(venueGroup,-w/2-.6,2.2,1.6,.18,4.4,4,0x151920);box(venueGroup,w/2+.6,2.2,1.6,.18,4.4,4,0x151920);return}const x=w/2+.38;box(venueGroup,-x,1.7,.2,.22,3.4,.22,0x202732);box(venueGroup,x,1.7,.2,.22,3.4,.22,0x202732);box(venueGroup,0,3.3,.2,w+1,.2,.22,0x202732)}
async function model(url){if(!url)return;try{const g=await loader.loadAsync(url);clearVenue();venueGroup.add(g.scene);status("场地模型已载入。") }catch(e){console.warn(e);procedural(currentVenue);status("场地模型载入失败，已使用预览模型。","warn")}}
function updateScreen(v){const s=v.screen;videoPlane.geometry.dispose();frame.geometry.dispose();videoPlane.geometry=new THREE.PlaneGeometry(s.widthM,s.heightM);frame.geometry=new THREE.BoxGeometry(s.widthM+.18,s.heightM+.18,.1);screenGroup.position.fromArray(s.position||[0,s.heightM/2+.25,0]);screenGroup.quaternion.identity();const [w,h]=s.resolution;ui.venueMeta.textContent=`${s.widthM.toFixed(2)} × ${s.heightM.toFixed(2)} m · ${w} × ${h} px`;ui.hudVenue.textContent=v.name;ui.hudScreen.textContent=`${s.widthM.toFixed(2)} × ${s.heightM.toFixed(2)} m · ${w} × ${h}`}
export function defaultView(){return currentVenue.viewpoints?.find(v=>v.id==="audience")||currentVenue.viewpoints?.[0]||fallback[0].viewpoints[0]}
export function renderViews(){ui.viewpoints.innerHTML="";(currentVenue.viewpoints||[]).forEach(v=>{const b=document.createElement("button");b.textContent=v.label;b.classList.toggle("active",v.id===currentView);b.onclick=()=>moveView(v.id);ui.viewpoints.append(b)})}
function desktop(v){rig.position.set(0,0,0);rig.rotation.set(0,0,0);camera.position.fromArray(v.position);controls.target.fromArray(v.target||currentVenue.screen.position);controls.update()}
export function applyXrView(v){const p=new THREE.Vector3();renderer.xr.getCamera(camera).getWorldPosition(p);rig.position.x+=v.position[0]-p.x;rig.position.z+=v.position[2]-p.z}
export function setCurrentView(id){currentView=id}
export function moveView(id="audience"){const v=currentVenue.viewpoints?.find(x=>x.id===id)||defaultView();currentView=v.id;ui.hudView.textContent=v.label;renderer.xr.isPresenting?applyXrView(v):desktop(v);renderViews();status(`已到${v.label}。`)}
export function applyVenue(id){currentVenue=venues.find(v=>v.id===id)||venues[0];ui.venue.value=currentVenue.id;updateScreen(currentVenue);procedural(currentVenue);if(currentVenue.modelUrl)model(currentVenue.modelUrl);currentView=defaultView().id;renderViews();moveView(currentView)}
export async function loadVenues(){try{const r=await fetch("./venues.json",{cache:"no-store"});if(r.ok){const d=await r.json();if(Array.isArray(d)&&d.length)venues=d}}catch{}ui.venue.innerHTML="";venues.forEach(v=>{const o=document.createElement("option");o.value=v.id;o.textContent=v.name;ui.venue.append(o)});const q=new URL(location.href).searchParams.get("venue");applyVenue(venues.some(v=>v.id===q)?q:venues[0].id)}
export async function playVideo(){try{await video.play();return true}catch(e){console.warn("video.play",e);return false}}
export async function setStream(stream,source){if(!stream)return;activeSource=source;video.srcObject=stream;if(video.readyState<HTMLMediaElement.HAVE_CURRENT_DATA)await new Promise(r=>{const done=()=>{video.removeEventListener("loadeddata",done);r()};video.addEventListener("loadeddata",done,{once:true});setTimeout(done,1200)});await playVideo();if(!videoTexture){videoTexture=new THREE.VideoTexture(video);videoTexture.colorSpace=THREE.SRGBColorSpace;videoTexture.minFilter=videoTexture.magFilter=THREE.LinearFilter;videoTexture.generateMipmaps=false}videoPlane.material=new THREE.MeshBasicMaterial({map:videoTexture,toneMapped:false,side:THREE.DoubleSide});ui.hudStream.textContent=source==="local"?"本机共享":"远程串流";ui.shareState.textContent="画面已映射";status(source==="local"?"共享画面已映射到场景屏幕。":"远程画面已接入场景屏幕。");}
export function resetStream(){video.srcObject=null;videoTexture?.dispose();videoTexture=null;videoPlane.material=standby;activeSource="none";ui.hudStream.textContent="无画面";ui.shareState.textContent="未共享"}
export function tickVideo(){if(videoTexture&&video.readyState>=HTMLMediaElement.HAVE_CURRENT_DATA)videoTexture.needsUpdate=true}
export function setMode(m){mode=m;$("#tab-quick").classList.toggle("active",m==="quick");$("#tab-venue").classList.toggle("active",m==="venue");ui.venueTools.classList.toggle("hide",m!=="venue");if(m==="quick"&&venues.some(v=>v.id==="quick-16x9"))applyVenue("quick-16x9")}
export function screenAhead(){const c=renderer.xr.isPresenting?renderer.xr.getCamera(camera):camera,p=new THREE.Vector3(),q=new THREE.Quaternion(),f=new THREE.Vector3(0,0,-1);c.getWorldPosition(p);c.getWorldQuaternion(q);f.applyQuaternion(q);screenGroup.position.copy(p).addScaledVector(f,2.2);screenGroup.quaternion.copy(q);status("屏幕已移到视线前方 2.2 米。")}
