async function ensureAudio(){if(!ac)ac=new(window.AudioContext||window.webkitAudioContext)();if(ac.state==='suspended')await ac.resume();if(master)return;master=ac.createGain();master.gain.value=.72;comp=ac.createDynamicsCompressor();comp.threshold.value=-14;comp.knee.value=12;comp.ratio.value=5;comp.attack.value=.004;comp.release.value=.18;master.connect(comp).connect(ac.destination);noiseBuffer=makeNoise()}
function makeNoise(){const b=ac.createBuffer(1,ac.sampleRate*3,ac.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=Math.random()*2-1;return b}
function osc(n,t,d,g,type='triangle',cut=2600,pan=0){if(!ac||voices>=MAXV)return;voices++;const o=ac.createOscillator(),f=ac.createBiquadFilter(),v=ac.createGain(),p=ac.createStereoPanner();o.type=type;o.frequency.value=midi(n);f.type='lowpass';f.frequency.value=cut;f.Q.value=1.5;v.gain.setValueAtTime(.0001,t);v.gain.exponentialRampToValueAtTime(Math.max(.0002,g),t+.007);v.gain.exponentialRampToValueAtTime(.0001,t+d);p.pan.value=pan;o.connect(f).connect(v).connect(p).connect(master);o.start(t);o.stop(t+d+.03);o.onended=()=>voices=Math.max(0,voices-1)}
function nse(t,d,g,f=5000,q=2,pan=0){if(!ac||voices>=MAXV)return;voices++;const s=ac.createBufferSource(),bp=ac.createBiquadFilter(),v=ac.createGain(),p=ac.createStereoPanner();s.buffer=noiseBuffer;bp.type='bandpass';bp.frequency.value=f;bp.Q.value=q;v.gain.setValueAtTime(g,t);v.gain.exponentialRampToValueAtTime(.0001,t+d);p.pan.value=pan;s.connect(bp).connect(v).connect(p).connect(master);s.start(t);s.stop(t+d+.02);s.onended=()=>voices=Math.max(0,voices-1)}
function sweep(n,t,d,g,a,b,pan=0){if(!ac||voices>=MAXV)return;voices++;const o=ac.createOscillator(),f=ac.createBiquadFilter(),v=ac.createGain(),p=ac.createStereoPanner();o.type='sawtooth';o.frequency.value=midi(n);f.type='bandpass';f.Q.value=4;f.frequency.setValueAtTime(Math.max(100,a),t);f.frequency.exponentialRampToValueAtTime(Math.max(100,b),t+d*.92);v.gain.setValueAtTime(.0001,t);v.gain.exponentialRampToValueAtTime(g,t+.012);v.gain.exponentialRampToValueAtTime(.0001,t+d);p.pan.value=pan;o.connect(f).connect(v).connect(p).connect(master);o.start(t);o.stop(t+d+.03);o.onended=()=>voices=Math.max(0,voices-1)}
function kick(t,g=.08){if(!ac)return;const o=ac.createOscillator(),v=ac.createGain();o.frequency.setValueAtTime(160,t);o.frequency.exponentialRampToValueAtTime(42,t+.12);v.gain.setValueAtTime(g,t);v.gain.exponentialRampToValueAtTime(.0001,t+.17);o.connect(v).connect(master);o.start(t);o.stop(t+.18)}
function qTime(){return Math.ceil(ac.currentTime/EIGHTH)*EIGHTH+.002}
function morph(n,x,y){n.len=x<.33?8:x<.72?12:16;n.density=.18+.72*y;n.prob=.62+.36*y;n.random=.04+.34*y;n.scale=.35+.75*y;const base=n.base;const target=Math.max(1,Math.round(n.len*n.density));const next=Array(16).fill(0);for(let i=0;i<n.len;i++){const src=base[i%base.length]||0;if(src)next[i]=src}let count=next.slice(0,n.len).filter(Boolean).length;const seed=Math.floor(x*31+y*47+n.phase*17);let guard=0;while(count<target&&guard++<64){const i=(seed*7+guard*5)%n.len;if(!next[i]){next[i]=(guard%5===0)?2:1;count++}}while(count>target&&guard++<128){const i=(seed*3+guard*7)%n.len;if(next[i]===1){next[i]=0;count--}}n.pattern=next;n.phase=x}
function playStep(n,t,val,heat){const pan=(n.x-.5)*1.4,g=(val===2?1.25:1)*(.25+.75*heat);if(n.id==='F'){if(tick%4===0){[45,52,57].forEach((m,i)=>osc(m,t,.9,.006*g*(1-i*.18),'triangle',900+700*n.scale,(i-1)*.2));}else if(Math.random()<n.random)nse(t,.09,.003*g,4200+3200*n.scale,1.2,pan)}else if(n.id==='P'){if(val===2||tick%4===0)kick(t,.07*g);else nse(t,.035,.006*g,7800,3,pan)}else if(n.id==='R'){const m=n.notes[(tick+Math.floor(n.phase*4))%n.notes.length];osc(m,t,.08,.011*g,'square',2200+3200*n.scale,pan);if(val===2)nse(t+.02,.025,.004*g,6200,5,-pan)}else if(n.id==='O'){const m=n.notes[(tick*2+Math.floor(n.phase*8))%n.notes.length];osc(m,t,.055,.009*g,'triangle',4200+3500*n.scale,Math.sin(tick*.8)*.6)}else if(n.id==='X'){if(val===2)nse(t,.04,.011*g,5200,6,pan);const root=[50,53,48,45][Math.floor(n.phase*4)%4];[root,root+7,root+12].forEach((m,i)=>osc(m,t,.22,.007*g,'triangle',1500+700*i,(i-1)*.15))}else if(n.id==='B'){nse(t,.025,.016*g,7000+1800*n.scale,4,pan);if(val===2){osc(89,t,.05,.012*g,'square',8000,.4);kick(t+.06,.04*g)}}else if(n.id==='I'){if(val===2||tick%4===0){kick(t,.12*g);osc(31,t,.65,.028*g,'sine',520,0);nse(t,.12,.012*g,1100,1.1,0)}}else if(n.id==='L'){sweep(72-Math.floor(n.scale*12),t,.36,.006*g,5200,520,-.35);if(val===2)nse(t+.08,.18,.004*g,3600,1.1,.35)}}
function enterPhrase(n){const t=qTime();if(n.id==='F')sweep(45,t,1.5,.008,300,1800,-.3);if(n.id==='P')kick(t,.1);if(n.id==='R')sweep(57,t,.65,.009,500,4200,.35);if(n.id==='O')osc(81,t,.5,.01,'triangle',6000,.5);if(n.id==='X')nse(t,.1,.014,3400,3);if(n.id==='B'){nse(t,.12,.026,7600,2);osc(89,t,.08,.016,'square',8200,.4)}if(n.id==='I'){kick(t,.16);osc(31,t,1,.035,'sine',480,0)}if(n.id==='L')sweep(77,t,.8,.01,6500,350,-.4)}
function exitPhrase(n){const t=qTime();if(n.id==='B'||n.id==='I')nse(t,.3,.008,3200,1.2);else sweep(65,t,.55,.0045,2100,420,(n.x-.5))}
function schedule(){while(running&&nextTick<ac.currentTime+LOOK){if(tick%4===0){kick(nextTick,.018);osc(38,nextTick,.32,.004,'sine',500,0)}for(const n of NODES){if(n.heat<.04)continue;const step=tick%n.len,val=n.pattern[step]||0;if(val&&Math.random()<n.prob)playStep(n,nextTick,val,n.heat);n.heat*=.994}if(auto&&tick%8===0){const bar=tick/8|0;if(bar!==autoBar){autoBar=bar;if(bar%4===0){const route=['F','P','R','O','X','B','I','L'];activate(BY[route[autoStep++%route.length]],'auto')}}}nextTick+=EIGHTH;tick++}}
async function togglePlay(){await ensureAudio();running=!running;if(running){nextTick=ac.currentTime+.04;scheduler&&clearInterval(scheduler);scheduler=setInterval(schedule,18);document.querySelector('#play').textContent='■';document.querySelector('#play').classList.add('on')}else{clearInterval(scheduler);scheduler=null;document.querySelector('#play').textContent='▶';document.querySelector('#play').classList.remove('on')}}
function activate(n,source='pointer'){if(current===n)return;previous=current;if(previous){exitPhrase(previous);residue(previous);history.push(previous.id);if(history.length>12)history.shift()}for(const o of NODES)if(o.f===n.f&&o!==n)o.heat*=.45;current=n;n.heat=1;enterPhrase(n);eventBurst(n,.9);if(source==='auto')morph(n,.45+.45*Math.random(),.45+.4*Math.random())}
function deactivate(){if(!current)return;exitPhrase(current);residue(current);previous=current;history.push(current.id);if(history.length>12)history.shift();current=null}
function hit(x,y){let best=null,bd=1e9;for(const n of NODES){const dx=x-n.x*W,dy=y-n.y*H,d=Math.hypot(dx,dy)/(n.r*Math.min(W,H));if(d<1.15&&d<bd){bd=d;best=n}}return best}
function pos(e){const r=stage.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
stage.addEventListener('pointerdown',async e=>{if(e.target.closest?.('.dock'))return;e.preventDefault();app.focus();await ensureAudio();if(!running)await togglePlay();pointerDown=true;last={...pos(e),t:performance.now()};const n=hit(last.x,last.y);if(n)activate(n)});
stage.addEventListener('pointermove',e=>{const p=pos(e);if(!pointerDown)return;const n=hit(p.x,p.y);if(n&&n!==current)activate(n);else if(!n&&current)deactivate();if(current){const cx=current.x*W,cy=current.y*H,r=current.r*Math.min(W,H),x=clamp((p.x-(cx-r))/(2*r),0,1),y=clamp(1-(p.y-(cy-r))/(2*r),0,1),dt=Math.max(8,performance.now()-last.t),speed=Math.hypot(p.x-last.x,p.y-last.y)/dt;morph(current,x,y);current.heat=clamp(current.heat+speed*.08,.25,1);if(speed>.9&&performance.now()-last.t<120)eventBurst(current,.5+Math.min(1,speed));trail.push({x:p.x,y:p.y,t:performance.now(),g:current.g});if(trail.length>140)trail.shift()}last={...p,t:performance.now()}});
stage.addEventListener('pointerup',()=>{pointerDown=false;if(current)deactivate()});stage.addEventListener('pointercancel',()=>{pointerDown=false;if(current)deactivate()});
