function drawHUD(now){h.clearRect(0,0,W,H);h.lineCap='round';if(showLinks&&current){for(const id of current.next){const b=BY[id];h.strokeStyle='rgba(255,255,255,.12)';h.setLineDash([3,7]);h.beginPath();h.moveTo(current.x*W,current.y*H);h.lineTo(b.x*W,b.y*H);h.stroke();h.setLineDash([])}}
for(const n of NODES){const x=n.x*W,y=n.y*H,r=n.r*Math.min(W,H),active=n===current;h.strokeStyle=`rgba(255,255,255,${active?.78:.17})`;h.lineWidth=active?1.7:1;h.beginPath();h.arc(x,y,r*(active?1.03:1),0,Math.PI*2);h.stroke();h.fillStyle=`rgba(255,255,255,${active?.92:.48})`;h.font=`${Math.round(r*(active?.72:.55))}px "Segoe UI Symbol","Apple Symbols",sans-serif`;h.textAlign='center';h.textBaseline='middle';h.fillText(n.g,x,y-r*.06);
const cell=Math.max(2.4,Math.min(5,(r*1.25)/n.len)),gap=1.3,total=n.len*(cell+gap)-gap,x0=x-total/2,yy=y+r*.45,play=tick%n.len;for(let i=0;i<n.len;i++){const v=n.pattern[i]||0,a=i===play&&running?.9:v===2?.5:v?.23:.055;h.fillStyle=`rgba(255,255,255,${a})`;h.fillRect(x0+i*(cell+gap),yy,cell,cell*(v?1:.45))}
if(active){h.strokeStyle='rgba(255,255,255,.18)';h.beginPath();h.arc(x,y,r*(.58+n.scale*.5),0,Math.PI*2);h.stroke();const ry=r*.82*(1-current.random*.25);h.strokeStyle='rgba(255,255,255,.08)';h.beginPath();h.moveTo(x-r*.75,y);h.lineTo(x+r*.75,y);h.moveTo(x,y-r*.75);h.lineTo(x,y+r*.75);h.stroke();h.fillStyle='rgba(255,255,255,.35)';h.font='16px "Segoe UI Symbol",sans-serif';h.fillText(current.g,x+r*(current.phase*1.5-.75),y-ry*(current.density-.5));}}
trail=trail.filter(p=>now-p.t<1700);if(trail.length>1){h.beginPath();trail.forEach((p,i)=>i?h.lineTo(p.x,p.y):h.moveTo(p.x,p.y));h.strokeStyle='rgba(255,255,255,.12)';h.stroke()}h.fillStyle='rgba(255,255,255,.34)';h.font='17px "Segoe UI Symbol",sans-serif';h.textAlign='left';h.fillText('◌  ●  ➜  ↻  ╳  ✦  ⊙  ↶',14,23);h.textAlign='right';h.fillText(`${current?current.g:'○'}  ${String(NODES.filter(n=>n.heat>.08).length).padStart(2,'0')}`,W-14,23)}
let lastT=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min(.05,(now-lastT)/1000);lastT=now;updateParticles(dt,now);renderGL();drawHUD(now)}requestAnimationFrame(frame);

document.querySelector('#play').onclick=togglePlay;document.querySelector('#auto').onclick=async()=>{await ensureAudio();if(!running)await togglePlay();auto=!auto;document.querySelector('#auto').classList.toggle('on',auto);autoStep=0;autoBar=-1};document.querySelector('#links').onclick=()=>{showLinks=!showLinks;document.querySelector('#links').classList.toggle('on',showLinks)};document.querySelector('#panic').onclick=()=>{for(const n of NODES)n.heat=0;particles=particles.filter(p=>p.life>100);current=null;previous=null;history=[];trail=[];auto=false;document.querySelector('#auto').classList.remove('on')};
async function toggleFull(){const fs=document.fullscreenElement||document.webkitFullscreenElement;if(fs){try{await(document.exitFullscreen?.()||document.webkitExitFullscreen?.())}catch{}stageMode=false;app.classList.remove('stageMode');setTimeout(resize,60);return}try{const fn=document.documentElement.requestFullscreen||document.documentElement.webkitRequestFullscreen;if(fn){await fn.call(document.documentElement);setTimeout(resize,60);return}}catch{}stageMode=!stageMode;app.classList.toggle('stageMode',stageMode);setTimeout(resize,60)}
document.querySelector('#full').onclick=toggleFull;document.addEventListener('fullscreenchange',()=>setTimeout(resize,60));app.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='f')toggleFull();if(e.key==='Escape'&&stageMode){stageMode=false;app.classList.remove('stageMode');resize()}});
