const CFG={fps:60,loopSeconds:30,loopFrames:1800,majorCols:12,majorRows:7,memorySubX:6,memorySubY:6,marginX:.055,marginY:.075,seed:160826,bg:[7,7,4],ink:[232,234,223]};
let loopOriginFrame=0,paused=false,debug=false,G={},C={};
function setup(){pixelDensity(1);frameRate(CFG.fps);createCanvas(windowWidth,windowHeight,P2D);noCursor();loopOriginFrame=frameCount;updateGrid()}
function windowResized(){resizeCanvas(windowWidth,windowHeight);updateGrid()}
function draw(){const f=paused?C.loopFrame:frameCount-loopOriginFrame;setLoopFrame(f);background(...CFG.bg);drawBaseGrid();drawConstraint();drawIndexField();if(C.recall>.05)drawHistoricalLead();drawQuantizedMemory();drawHistoricalTopology();drawMechanicalGlyphLanguage();if(debug)drawDebug()}
function setLoopFrame(frame){const f=((frame%CFG.loopFrames)+CFG.loopFrames)%CFG.loopFrames;C.loopFrame=f;C.loopT=f/CFG.loopFrames;C.time=f/CFG.fps;C.inputActivity=cyclicWindow(C.loopT,0,.27,.06);C.absorption=cyclicWindow(C.loopT,.16,.58,.10);C.recall=cyclicWindow(C.loopT,.46,.82,.09);C.autonomy=cyclicWindow(C.loopT,.69,.98,.08);C.density=constrain(.12+C.absorption*.52+C.recall*.24+C.autonomy*.08,0,1);C.pressure=constrain(C.inputActivity*.22+C.absorption*.42+C.recall*.62,0,1);C.historyDepth=constrain(C.absorption*.55+C.recall*.95+C.autonomy*.78,0,1)}
function updateGrid(){const target=16/9;let vw=width,vh=height;if(vw/vh>target)vw=vh*target;else vh=vw/target;G.left=(width-vw)/2+vw*CFG.marginX;G.right=(width+vw)/2-vw*CFG.marginX;G.top=(height-vh)/2+vh*CFG.marginY;G.bottom=(height+vh)/2-vh*CFG.marginY;G.dx=(G.right-G.left)/CFG.majorCols;G.dy=(G.bottom-G.top)/CFG.majorRows;G.microCols=CFG.majorCols*CFG.memorySubX;G.microRows=CFG.majorRows*CFG.memorySubY;G.microDx=G.dx/CFG.memorySubX;G.microDy=G.dy/CFG.memorySubY;G.unit=min(G.dx,G.dy)}
const majorX=c=>G.left+c*G.dx,majorY=r=>G.top+r*G.dy,microX=c=>G.left+(c+.5)*G.microDx,microY=r=>G.top+(r+.5)*G.microDy;
function hash2(a,b,s){const n=Math.sin(a*127.1+b*311.7+s*74.7)*43758.5453;return n-Math.floor(n)}
function smooth01(v){v=constrain(v,0,1);return v*v*(3-2*v)}
function cyclicWindow(p,start,end,feather){const inn=smooth01((p-start)/feather),out=1-smooth01((p-(end-feather))/feather);if(end>=start)return constrain(inn*out,0,1);return max(cyclicWindow(p,start,1,feather),cyclicWindow(p,0,end,feather))}
function pulse(phase,center,width){let d=abs(phase-center);d=min(d,1-d);let v=constrain(1-d/max(.0001,width),0,1);return v*v*(3-2*v)}
const ink=a=>stroke(CFG.ink[0],CFG.ink[1],CFG.ink[2],a),fillInk=a=>fill(CFG.ink[0],CFG.ink[1],CFG.ink[2],a);
function drawBaseGrid(){let a=10+C.absorption*9+C.recall*5;noFill();strokeWeight(max(.55,width/3840));for(let c=0;c<=CFG.majorCols;c++){ink(a*(c%3===0?1:.54));line(majorX(c),G.top,majorX(c),G.bottom)}for(let r=0;r<=CFG.majorRows;r++){ink(a*(r%2===0?1:.54));line(G.left,majorY(r),G.right,majorY(r))}noStroke();for(let r=0;r<=CFG.majorRows;r+=2)for(let c=0;c<=CFG.majorCols;c+=3){fillInk(22+C.historyDepth*22);const s=max(1.8,width/1800);rectMode(CENTER);rect(majorX(c),majorY(r),s,s)}rectMode(CORNER)}
function drawConstraint(){let presence=(.24+C.inputActivity*.34+C.absorption*.42+C.recall*.28)*.72;const sw=max(.55,width/4200);noFill();for(let r=0;r<CFG.majorRows;r++)for(let c=0;c<CFG.majorCols;c++){if(hash2(c,r,CFG.seed+31)<.72)continue;const down=hash2(c,r,CFG.seed+33)>.5;ink((12+33*C.historyDepth)*presence);strokeWeight(sw);line(majorX(c),down?majorY(r):majorY(r+1),majorX(c+1),down?majorY(r+1):majorY(r))}for(let r=0;r<CFG.majorRows;r++)for(let c=0;c<CFG.majorCols;c++){const p=pulse(C.loopT,hash2(c,r,CFG.seed+41),.052);if(p<.018)continue;const down=hash2(c,r,CFG.seed+43)>.5;ink((32+128*p)*presence);strokeWeight(sw*(1+p*.8));line(majorX(c),down?majorY(r):majorY(r+1),majorX(c+1),down?majorY(r+1):majorY(r))}for(const [i,c] of [0,3,6,9,12].entries()){const p=pulse((C.loopT+i*.17)%1,.18,.075);if(p<.015)continue;for(let edge=0;edge<2;edge++){const x=majorX(c),y=edge===0?G.top:G.bottom,s=G.unit*.11;noFill();ink((28+98*p)*presence);strokeWeight(sw);rectMode(CENTER);rect(x,y,s*2,s*2);noStroke();fillInk((65+155*p)*presence);rect(x,y,max(2,s*.25),max(2,s*.25))}}rectMode(CORNER)}
function drawIndexField(){const presence=(.20+C.inputActivity*.20+C.absorption*.60+C.recall*.34+C.autonomy*.14)*.66,cols=CFG.majorCols*2,rows=CFG.majorRows*2,sx=(G.right-G.left)/cols,sy=(G.bottom-G.top)/rows,sw=max(.55,width/4300);noFill();for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){if(hash2(c,r,CFG.seed+71)<.42)continue;const x=G.left+(c+.5)*sx,y=G.top+(r+.5)*sy,family=hash2(c,r,CFG.seed+73),phase=hash2(c,r,CFG.seed+79),active=pulse(C.loopT,phase,.035+.025*hash2(c,r,81)),lead=pulse((C.loopT+.08*C.recall)%1,phase,.045),alpha=(18+48*hash2(c,r,83)+135*max(active,lead*C.recall))*presence;ink(alpha);strokeWeight(sw*(active>.65?1.45:1));if(family<.30){const s=min(sx,sy)*(.24+.13*hash2(c,r,89));rectMode(CENTER);rect(x,y,s*2,s*2);if(hash2(c,r,91)>.80)rect(x,y,s*1.04,s*1.04)}else if(family<.63){const len=sx*(.23+.16*hash2(c,r,97));line(x-len,y,x+len,y)}else if(family<.83){const len=sx*.25,rise=sy*(hash2(c,r,101)>.5?.12:-.12);line(x-len,y+rise,x+len,y-rise)}else{const len=min(sx,sy)*.24;line(x,y-len,x,y+len)}}rectMode(CORNER)}
function drawHistoricalLead(){const rr=C.recall,aa=C.absorption,ii=C.inputActivity;C.recall*=.28;C.absorption*=.20;C.inputActivity=0;push();translate(-G.dx*.08*C.recall,0);drawConstraint();drawIndexField();pop();C.recall=rr;C.absorption=aa;C.inputActivity=ii}
function drawQuantizedMemory(){const presence=.10+C.absorption*.38+C.recall*.88+C.autonomy*.52,dashH=max(1,height/1800);noStroke();for(let r=0;r<G.microRows;r++){const age=r/max(1,G.microRows-1),fade=lerp(1,.14,pow(age,1.25));for(let c=0;c<G.microCols;c++){if(hash2(c,r,CFG.seed+131)<.49)continue;const phase=hash2(c,r,CFG.seed+137),active=pulse(C.loopT,phase,.028+.015*hash2(c,r,139)),old=(phase+.23+.11*hash2(c,r,141))%1,recalled=pulse(C.loopT,old,.036)*C.recall,value=max(active*(.30+C.absorption*.45),recalled),x=microX(c),y=microY(r),base=22+72*hash2(c,r,149),alpha=(base+142*value)*fade*presence;fillInk(alpha);if(hash2(c,r,CFG.seed+151)>.925){const side=min(G.microDx,G.microDy)*(.30+.20*hash2(c,r,157));rectMode(CENTER);rect(x,y,side,side)}else{const len=G.microDx*(.42+.35*hash2(c,r,163));rectMode(CENTER);rect(x,y,len,dashH)}}}for(let chain=0;chain<7;chain++){const a=pulse(C.loopT,(.11+chain*.137)%1,.075)*C.recall;if(a<.012)continue;const start=floor(hash2(chain,0,CFG.seed+173)*(G.microCols-16)),stride=3+(chain%4);for(let r=1;r<G.microRows-1;r+=stride){const c=(start+r*(chain%2===0?1:-1)+G.microCols)%G.microCols,x=microX(c),y=microY(r),side=min(G.microDx,G.microDy)*.52;fillInk((70+150*a)*(1-.72*r/G.microRows));rectMode(CENTER);rect(x,y,side,side)}}rectMode(CORNER);ink(85*presence);strokeWeight(max(.55,width/4300));line(G.left,G.top+G.microDy*.22,G.right,G.top+G.microDy*.22)}
const topoAnchors=[[2,2],[4,4],[6,1],[8,5],[10,2],[11,4]],topoEdges=[[0,1],[1,2],[2,3],[3,4],[4,5],[1,3],[2,4]];
function drawHistoricalTopology(){const gate=pulse(C.loopT,.66,.13)*C.recall*C.historyDepth;if(gate<.018)return;const pts=topoAnchors.map(([c,r])=>[majorX(c)+G.dx*.5,majorY(r)+G.dy*.5]);noFill();strokeWeight(max(.6,width/4600));for(let i=0;i<topoEdges.length;i++){const [a,b]=topoEdges[i],local=pulse((C.loopT+i*.019)%1,.66,.14);ink((18+86*local)*gate);line(pts[a][0],pts[a][1],pts[b][0],pts[b][1])}for(let i=0;i<pts.length;i++){const [x,y]=pts[i],s=G.unit*(.035+.018*(i%3));drawOutlineGlyph(i%6,x,y,s,255*gate,false)}}
function drawMechanicalGlyphLanguage(){const global=.48*(.18+C.absorption*.38+C.recall*.82+C.autonomy*.36);for(let z=0;z<5;z++)drawAddressableZone(z,global);drawProgressSequence(global);drawPersistentMemoryAnchors(global)}
function belongsToZone(z,c,r,cols,rows){if(z===0)return r<=1&&c%2===0;if(z===1)return c<=3&&r>=3&&r<=rows-4;if(z===2)return(abs(c-cols/2)<=1||abs(r-rows/2)<=1)&&c>4&&c<cols-5;if(z===3)return c>=cols-4&&r>=3&&r<=rows-4;if(z===4){const t=r/max(1,rows-1),target=round(cols*(.30+.42*t));return abs(c-target)<=1}return false}
function drawAddressableZone(z,global){const centers=[.06,.22,.39,.57,.76],intensity=max(pulse(C.loopT,centers[z],.055+z*.004),pulse(C.loopT,(centers[z]+.31)%1,.07)*C.recall*.70)*global;if(intensity<.01)return;const cols=CFG.majorCols*2,rows=CFG.majorRows*2,sx=(G.right-G.left)/cols,sy=(G.bottom-G.top)/rows;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){if(!belongsToZone(z,c,r,cols,rows)||hash2(c,r,211+z)<.55)continue;const x=G.left+(c+.5)*sx,y=G.top+(r+.5)*sy,local=.45+.55*pulse(C.loopT,(centers[z]+hash2(c,r,223)*.055)%1,.035),alpha=180*intensity*local,glyph=floor(hash2(c,r,257)*8)%8;drawOutlineGlyph(glyph,x,y,min(sx,sy)*(z===4?.11:.095),alpha,z===4)}}
function drawProgressSequence(global){const segments=CFG.majorCols,progress=.5-.5*cos(TWO_PI*C.loopT),active=progress*(segments-1),y=G.top+G.dy*.38;for(let i=0;i<segments;i++){const a=constrain(1-abs(i-active)/2.2,0,1);if(a<.02)continue;const x=majorX(i)+G.dx*.5,alpha=115*a*global*(.35+.65*C.pressure);if(i%3===0)drawOutlineGlyph(2,x,y,G.unit*.045,alpha,false);else{noStroke();fillInk(alpha);circle(x,y,max(1.5,G.unit*.018))}}}
function drawPersistentMemoryAnchors(global){if(C.historyDepth<.08)return;for(const [i,[c,r]] of [[0,[2,2]],[1,[5,4]],[2,[8,1]],[3,[10,5]]].entries()){const x=majorX(c)+G.dx*.5,y=majorY(r)+G.dy*.5,a=(26+76*C.historyDepth+52*C.recall*pulse(C.loopT,(.64+i*.07)%1,.05))*global;drawOutlineGlyph(i%2===0?6:4,x,y,G.unit*.07,a,false)}}
function drawOutlineGlyph(type,x,y,s,alpha,echo){push();translate(x,y);stroke(CFG.ink[0],CFG.ink[1],CFG.ink[2],alpha);strokeWeight(max(.6,width/4200));noFill();const q=s;switch(type%8){case 0:noStroke();fillInk(alpha);circle(0,0,max(1.5,q*.42));break;case 1:line(-q,0,q,0);break;case 2:rectMode(CENTER);rect(0,0,q*1.45,q*1.45);break;case 3:triangle(0,-q,-q*.92,q*.72,q*.92,q*.72);break;case 4:beginShape();vertex(0,-q);vertex(q,0);vertex(0,q);vertex(-q,0);endShape(CLOSE);break;case 5:line(-q,-q,q,q);line(q,-q,-q,q);break;case 6:circle(0,0,q*1.8);if(echo)circle(0,0,q*.82);break;case 7:arc(0,0,q*2,q*2,-PI*.82,PI*.54);line(-q*.68,-q*.72,-q*.98,-q*.38);line(-q*.68,-q*.72,-q*.40,-q*.35)}rectMode(CORNER);pop()}
function drawDebug(){cursor();push();noStroke();fillInk(175);textSize(12);textAlign(LEFT,TOP);text(`R4 WEB  ${nf(C.time,2,2)} / 30.00  FRAME ${C.loopFrame} / ${CFG.loopFrames}  FPS ${nf(frameRate(),2,1)}  ${width}×${height}`,16,16);pop()}
function keyPressed(){if(key===' '){paused=!paused;return false}if(key==='r'||key==='R'){loopOriginFrame=frameCount;setLoopFrame(0)}if(key==='d'||key==='D'){debug=!debug;if(!debug)noCursor()}if(key==='s'||key==='S')saveCanvas('NFI-R4-WEB','png');if(key==='f'||key==='F')fullscreen(!fullscreen())}
